# Generated by Django 3.2 on 2021-04-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210426_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin_no',
            field=models.CharField(max_length=100),
        ),
    ]
